#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : xslTNG
Version  : 1.3.1
Release  : 1
URL      : file:///aot/build/clearlinux/packages/xslTNG/xslTNG-1.3.1.tar.gz
Source0  : file:///aot/build/clearlinux/packages/xslTNG/xslTNG-1.3.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1-only MIT
Requires: xslTNG-bin = %{version}-%{release}
BuildRequires : bash
BuildRequires : buildreq-cmake
BuildRequires : ca-certs
BuildRequires : ca-certs-static
BuildRequires : ccache
BuildRequires : click
BuildRequires : curl
BuildRequires : curl-bin
BuildRequires : curl-dev
BuildRequires : curl-lib
BuildRequires : findutils
BuildRequires : git
BuildRequires : gradle
BuildRequires : gradle-bin
BuildRequires : gradle-dev
BuildRequires : mlocate
BuildRequires : openjdk13
BuildRequires : openjdk13-dev
BuildRequires : openssl-dev
BuildRequires : openssl-lib
BuildRequires : p11-kit
BuildRequires : pcre-dev
BuildRequires : pcre-extras
BuildRequires : python3
BuildRequires : python3-dev
BuildRequires : xmlstarlet
BuildRequires : zlib-dev

%description
DocBook Sample Documents
========================
This directory contains a few small sample documents. The reference
guide and other introductions use these documents as examples.

%package bin
Summary: bin components for the xslTNG package.
Group: Binaries

%description bin
bin components for the xslTNG package.


%prep
%setup -q -n xslTNG
cd %{_builddir}/xslTNG

%build
## build_prepend content
export JAVA_HOME=/usr/lib/jvm/java-1.13.0-openjdk
alias java=java13
gradle --gradle-user-home ./cache zipStage
## build_prepend end
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1616461153
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$FFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$FFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
%cmake .. -DCMAKE_INSTALL_LIBDIR=/usr/lib -DLIB_INSTALL_DIR=/usr/lib -DLIB_SUFFIX=
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1616461153
rm -rf %{buildroot}
pushd clr-build
%make_install
popd
## install_append content
mkdir -p %{buildroot}/usr/bin
ln -sf /opt/xslTNG/bin/docbook %{buildroot}/usr/bin/docbook
## install_append end

%files
%defattr(-,root,root,-)
/opt/xslTNG/LICENSE
/opt/xslTNG/README.md
/opt/xslTNG/bin/docbook
/opt/xslTNG/docker/Dockerfile
/opt/xslTNG/docker/README
/opt/xslTNG/libs/docbook-xslTNG-1.3.1.jar
/opt/xslTNG/libs/lib/Saxon-HE-10.2.jar
/opt/xslTNG/libs/lib/commons-codec-1.10.jar
/opt/xslTNG/libs/lib/commons-logging-1.2.jar
/opt/xslTNG/libs/lib/hamcrest-core-1.3.jar
/opt/xslTNG/libs/lib/httpclient-4.5.5.jar
/opt/xslTNG/libs/lib/httpcore-4.4.9.jar
/opt/xslTNG/libs/lib/isorelax-20030108.jar
/opt/xslTNG/libs/lib/jing-20181222.jar
/opt/xslTNG/libs/lib/junit-4.13.jar
/opt/xslTNG/libs/lib/metadata-extractor-2.14.0.jar
/opt/xslTNG/libs/lib/sinclude-0.9.2.jar
/opt/xslTNG/libs/lib/slf4j-api-1.7.25.jar
/opt/xslTNG/libs/lib/slf4j-simple-1.7.25.jar
/opt/xslTNG/libs/lib/xercesImpl-2.9.1.jar
/opt/xslTNG/libs/lib/xml-apis-1.4.01.jar
/opt/xslTNG/libs/lib/xmlresolver-1.1.0.jar
/opt/xslTNG/libs/lib/xmpcore-6.0.6.jar
/opt/xslTNG/resources/css/docbook-paged.css
/opt/xslTNG/resources/css/docbook-screen.css
/opt/xslTNG/resources/css/docbook-toc.css
/opt/xslTNG/resources/css/docbook.css
/opt/xslTNG/resources/css/oxy-markup.css
/opt/xslTNG/resources/css/print-book.css
/opt/xslTNG/resources/css/print-paper.css
/opt/xslTNG/resources/css/print-verso.css
/opt/xslTNG/resources/css/print.css
/opt/xslTNG/resources/css/prism.css
/opt/xslTNG/resources/css/speaker-notes.css
/opt/xslTNG/resources/css/xlink.css
/opt/xslTNG/resources/js/annotations.js
/opt/xslTNG/resources/js/chunk-nav.js
/opt/xslTNG/resources/js/controls.js
/opt/xslTNG/resources/js/persistent-toc.js
/opt/xslTNG/resources/js/prism.js
/opt/xslTNG/resources/js/xlink.js
/opt/xslTNG/samples/README
/opt/xslTNG/samples/article.xml
/opt/xslTNG/samples/css/docbook-paged.css
/opt/xslTNG/samples/css/docbook-screen.css
/opt/xslTNG/samples/css/docbook-toc.css
/opt/xslTNG/samples/css/docbook.css
/opt/xslTNG/samples/css/oxy-markup.css
/opt/xslTNG/samples/css/print-book.css
/opt/xslTNG/samples/css/print-paper.css
/opt/xslTNG/samples/css/print-verso.css
/opt/xslTNG/samples/css/print.css
/opt/xslTNG/samples/css/prism.css
/opt/xslTNG/samples/css/speaker-notes.css
/opt/xslTNG/samples/css/xlink.css
/opt/xslTNG/samples/custom.xsl
/opt/xslTNG/samples/js/annotations.js
/opt/xslTNG/samples/js/chunk-nav.js
/opt/xslTNG/samples/js/controls.js
/opt/xslTNG/samples/js/persistent-toc.js
/opt/xslTNG/samples/js/prism.js
/opt/xslTNG/samples/js/xlink.js
/opt/xslTNG/xslt/VERSION.xsl
/opt/xslTNG/xslt/catalog.xml
/opt/xslTNG/xslt/docbook.xsl
/opt/xslTNG/xslt/drivers.xsl
/opt/xslTNG/xslt/locale/af.xml
/opt/xslTNG/xslt/locale/am.xml
/opt/xslTNG/xslt/locale/ar.xml
/opt/xslTNG/xslt/locale/as.xml
/opt/xslTNG/xslt/locale/ast.xml
/opt/xslTNG/xslt/locale/az.xml
/opt/xslTNG/xslt/locale/bg.xml
/opt/xslTNG/xslt/locale/bn.xml
/opt/xslTNG/xslt/locale/bn_in.xml
/opt/xslTNG/xslt/locale/bs.xml
/opt/xslTNG/xslt/locale/ca.xml
/opt/xslTNG/xslt/locale/cs.xml
/opt/xslTNG/xslt/locale/cy.xml
/opt/xslTNG/xslt/locale/da.xml
/opt/xslTNG/xslt/locale/de.xml
/opt/xslTNG/xslt/locale/el.xml
/opt/xslTNG/xslt/locale/en.xml
/opt/xslTNG/xslt/locale/eo.xml
/opt/xslTNG/xslt/locale/es.xml
/opt/xslTNG/xslt/locale/et.xml
/opt/xslTNG/xslt/locale/eu.xml
/opt/xslTNG/xslt/locale/fa.xml
/opt/xslTNG/xslt/locale/fi.xml
/opt/xslTNG/xslt/locale/fr.xml
/opt/xslTNG/xslt/locale/ga.xml
/opt/xslTNG/xslt/locale/gl.xml
/opt/xslTNG/xslt/locale/gu.xml
/opt/xslTNG/xslt/locale/he.xml
/opt/xslTNG/xslt/locale/hi.xml
/opt/xslTNG/xslt/locale/hr.xml
/opt/xslTNG/xslt/locale/hu.xml
/opt/xslTNG/xslt/locale/id.xml
/opt/xslTNG/xslt/locale/is.xml
/opt/xslTNG/xslt/locale/it.xml
/opt/xslTNG/xslt/locale/ja.xml
/opt/xslTNG/xslt/locale/ka.xml
/opt/xslTNG/xslt/locale/kn.xml
/opt/xslTNG/xslt/locale/ko.xml
/opt/xslTNG/xslt/locale/ky.xml
/opt/xslTNG/xslt/locale/la.xml
/opt/xslTNG/xslt/locale/lt.xml
/opt/xslTNG/xslt/locale/lv.xml
/opt/xslTNG/xslt/locale/ml.xml
/opt/xslTNG/xslt/locale/mn.xml
/opt/xslTNG/xslt/locale/mr.xml
/opt/xslTNG/xslt/locale/nb.xml
/opt/xslTNG/xslt/locale/nds.xml
/opt/xslTNG/xslt/locale/nl.xml
/opt/xslTNG/xslt/locale/nn.xml
/opt/xslTNG/xslt/locale/or.xml
/opt/xslTNG/xslt/locale/pa.xml
/opt/xslTNG/xslt/locale/pl.xml
/opt/xslTNG/xslt/locale/pt.xml
/opt/xslTNG/xslt/locale/pt_br.xml
/opt/xslTNG/xslt/locale/ro.xml
/opt/xslTNG/xslt/locale/ru.xml
/opt/xslTNG/xslt/locale/sk.xml
/opt/xslTNG/xslt/locale/sl.xml
/opt/xslTNG/xslt/locale/sq.xml
/opt/xslTNG/xslt/locale/sr.xml
/opt/xslTNG/xslt/locale/sr_Latn.xml
/opt/xslTNG/xslt/locale/sv.xml
/opt/xslTNG/xslt/locale/ta.xml
/opt/xslTNG/xslt/locale/te.xml
/opt/xslTNG/xslt/locale/th.xml
/opt/xslTNG/xslt/locale/tl.xml
/opt/xslTNG/xslt/locale/tr.xml
/opt/xslTNG/xslt/locale/uk.xml
/opt/xslTNG/xslt/locale/ur.xml
/opt/xslTNG/xslt/locale/vi.xml
/opt/xslTNG/xslt/locale/xh.xml
/opt/xslTNG/xslt/locale/zh.xml
/opt/xslTNG/xslt/locale/zh_cn.xml
/opt/xslTNG/xslt/locale/zh_tw.xml
/opt/xslTNG/xslt/main.xsl
/opt/xslTNG/xslt/modules/admonitions.xsl
/opt/xslTNG/xslt/modules/annotations.xsl
/opt/xslTNG/xslt/modules/attributes.xsl
/opt/xslTNG/xslt/modules/bibliography.xsl
/opt/xslTNG/xslt/modules/blocks.xsl
/opt/xslTNG/xslt/modules/chunk-cleanup.xsl
/opt/xslTNG/xslt/modules/chunk-output.xsl
/opt/xslTNG/xslt/modules/chunk.xsl
/opt/xslTNG/xslt/modules/components.xsl
/opt/xslTNG/xslt/modules/divisions.xsl
/opt/xslTNG/xslt/modules/errors.xsl
/opt/xslTNG/xslt/modules/footnotes.xsl
/opt/xslTNG/xslt/modules/functions.xsl
/opt/xslTNG/xslt/modules/gentext.xsl
/opt/xslTNG/xslt/modules/glossary.xsl
/opt/xslTNG/xslt/modules/head.xsl
/opt/xslTNG/xslt/modules/highlight.xsl
/opt/xslTNG/xslt/modules/index.xsl
/opt/xslTNG/xslt/modules/info.xsl
/opt/xslTNG/xslt/modules/inlines.xsl
/opt/xslTNG/xslt/modules/links.xsl
/opt/xslTNG/xslt/modules/lists.xsl
/opt/xslTNG/xslt/modules/msgset.xsl
/opt/xslTNG/xslt/modules/objects.xsl
/opt/xslTNG/xslt/modules/profile.xsl
/opt/xslTNG/xslt/modules/programming.xsl
/opt/xslTNG/xslt/modules/publishers.xsl
/opt/xslTNG/xslt/modules/refentry.xsl
/opt/xslTNG/xslt/modules/sections.xsl
/opt/xslTNG/xslt/modules/shared.xsl
/opt/xslTNG/xslt/modules/space.xsl
/opt/xslTNG/xslt/modules/tablecals.xsl
/opt/xslTNG/xslt/modules/tablehtml.xsl
/opt/xslTNG/xslt/modules/templates.xml
/opt/xslTNG/xslt/modules/templates.xsl
/opt/xslTNG/xslt/modules/titlepage.xsl
/opt/xslTNG/xslt/modules/titles.xsl
/opt/xslTNG/xslt/modules/toc.xsl
/opt/xslTNG/xslt/modules/unhandled.xsl
/opt/xslTNG/xslt/modules/units.xsl
/opt/xslTNG/xslt/modules/variable.xsl
/opt/xslTNG/xslt/modules/verbatim.xsl
/opt/xslTNG/xslt/modules/xlink.xsl
/opt/xslTNG/xslt/modules/xref.xsl
/opt/xslTNG/xslt/olinkdb.xsl
/opt/xslTNG/xslt/param.xsl
/opt/xslTNG/xslt/parameter-maps.xsl
/opt/xslTNG/xslt/preprocess.xsl
/opt/xslTNG/xslt/print.xsl
/opt/xslTNG/xslt/speaker-notes.xsl
/opt/xslTNG/xslt/transforms/00-logstruct.xsl
/opt/xslTNG/xslt/transforms/10-xinclude.xsl
/opt/xslTNG/xslt/transforms/20-db4to5.xsl
/opt/xslTNG/xslt/transforms/30-transclude.xsl
/opt/xslTNG/xslt/transforms/50-normalize.xsl
/opt/xslTNG/xslt/transforms/60-annotations.xsl
/opt/xslTNG/xslt/transforms/70-xlinkbase.xsl
/opt/xslTNG/xslt/transforms/80-oxy-markup.xsl
/opt/xslTNG/xslt/xspec-driver.xsl

%files bin
%defattr(-,root,root,-)
/usr/bin/docbook
